from django.urls import path
from . import views
from .two_factor_views import login_view, verificar_codigo_view

urlpatterns = [
    path('', views.home_view, name='home'),
    path('terminos/', views.terminos_view, name='terminos'),
    path('privacidad/', views.privacidad_view, name='privacidad'),
    path('cookies/', views.cookies_view, name='cookies'),
    path('registro/', views.registro_view, name='registro'),
    path('api/registro/disponibilidad/', views.registro_disponibilidad_view, name='registro_disponibilidad'),
    path('registro/pendiente/', views.registro_pendiente_view, name='registro_pendiente'),
    path('verificacion-en-proceso/', views.verificacion_proceso, name='verificacion_proceso'),
    path('login/', login_view, name='login'),
    path('verificar-codigo/', verificar_codigo_view, name='verificar_codigo'),
    path('recuperar-contrasena/', views.forgot_password_view, name='forgot_password'),
    path('restablecer-contrasena/<str:token>/', views.reset_password_view, name='reset_password'),
    path('completar-perfil/', views.completar_perfil_view, name='completar_perfil'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/admin/', views.dashboard_admin_view, name='dashboard_admin'),
    path('dashboard/admin/donaciones/', views.admin_donaciones_view, name='admin_donaciones'),
    path('dashboard/admin/crear-admin/', views.crear_administrador, name='crear_administrador'),
    path('dashboard/admin/exportar/excel/', views.exportar_servicios_csv, name='exportar_servicios_csv'),
    path('dashboard/admin/exportar/pdf/', views.exportar_servicios_pdf, name='exportar_servicios_pdf'),
    path('dashboard/admin/aprobar/<uuid:usuario_id>/', views.aprobar_usuario_view, name='aprobar_usuario'),
    path('dashboard/admin/rechazar/<uuid:usuario_id>/', views.rechazar_usuario_view, name='rechazar_usuario'),
    path('api/admin/metrics/', views.admin_metrics_json, name='api_admin_metrics'),
    path('api/admin/donaciones/', views.admin_donaciones_json, name='api_admin_donaciones'),
    path('api/admin/metrics/revision/', views.admin_metrics_revision_json, name='api_admin_metrics_revision'),
    path('api/admin/metrics/wait/', views.admin_metrics_wait_json, name='api_admin_metrics_wait'),
    path('api/donaciones-stats/', views.donaciones_stats_json, name='api_donaciones_stats'),
    path('api/donaciones-lista/', views.donaciones_lista_json, name='api_donaciones_lista'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('dashboard/paciente/', views.dashboard_discapacitado, name='dashboard_discapacitado'),
    path('dashboard/paciente/update-emergency-contact/', views.update_emergency_contact, name='update_emergency_contact'),
    path('dashboard/paciente/emergency-support/', views.trigger_emergency_support, name='trigger_emergency_support'),
    path('dashboard/patient/update-emergency-contact/', views.update_emergency_contact, name='update_emergency_contact_en'),
    path('dashboard/enfermero/', views.dashboard_enfermero, name='dashboard_enfermero'),
    path('dashboard/enfermero/servicios/', views.enfermero_servicios_view, name='enfermero_servicios'),
    path('dashboard/enfermero/emergencia/', views.enfermero_emergencia, name='enfermero_emergencia'),
    path('api/notificaciones/', views.ultimas_solicitudes_json, name='api_notificaciones'),
    path('api/wompi/generar-firma/', views.generar_firma_wompi, name='generar_firma_wompi'),
    path('wompi/resultado/', views.wompi_resultado, name='wompi_resultado'),
    path('epayco/webhook/', views.epayco_webhook, name='epayco_webhook'),
    path('peticiones/<uuid:peticion_id>/postular/', views.postular_peticion, name='postular_peticion'),
    path('peticiones/<uuid:peticion_id>/retirar-postulacion/', views.retirar_postulacion, name='retirar_postulacion'),
    path('peticiones/<uuid:peticion_id>/cancelar/', views.cancelar_solicitud, name='cancelar_solicitud'),
    path('dashboard/enfermero/servicios/<uuid:peticion_id>/postular/', views.postular_peticion, name='postular_servicio'),
    path('servicios/<int:servicio_id>/iniciar-viaje/', views.iniciar_viaje, name='iniciar_viaje'),
    path('servicios/<int:servicio_id>/actualizar/', views.actualizar_estado_servicio, name='actualizar_estado_servicio'),
    path('servicios/<int:servicio_id>/calificar/', views.calificar_enfermero, name='calificar_enfermero'),
    path('servicios/<int:servicio_id>/calificar-paciente/', views.calificar_paciente, name='calificar_paciente'),
    path('postulaciones/<uuid:postulacion_id>/aceptar/', views.aceptar_enfermero, name='aceptar_enfermero'),
    path('dashboard/paciente/peticiones/<uuid:peticion_id>/aceptar/<uuid:enfermero_id>/', views.aceptar_postulacion, name='aceptar_postulacion'),
    path('solicitar-ayuda/', views.solicitar_ayuda_view, name='solicitar_ayuda'),
    path('aceptar-solicitud/', views.aceptar_solicitud_view, name='aceptar_solicitud'),
    path('dashboard/update-profile-picture/', views.update_profile_picture, name='update_profile_picture'),
]
