"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url
import re
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent

env = environ.Env(
    DEBUG=(bool, False),
    DB_PORT=(int, 5432),
)

_env_candidates = [PROJECT_ROOT / '.env', BASE_DIR / '.env']
_loaded_env_file = None
for _env_file in _env_candidates:
    if _env_file.exists():
        environ.Env.read_env(_env_file)
        _loaded_env_file = _env_file
        break

if 'WOMPI_INTEGRITY_SECRET' not in os.environ and _loaded_env_file is not None:
    try:
        raw = _loaded_env_file.read_text(encoding='utf-8')
        match = re.search(r'^\s*WOMPI_INTEGRITY_SECRET\s*=\s*(.+?)\s*$', raw, flags=re.MULTILINE)
        if match:
            value = match.group(1).strip()
            if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
                value = value[1:-1]
            if value:
                os.environ['WOMPI_INTEGRITY_SECRET'] = value
    except Exception:
        pass

SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost', 'sulk-punctured-boned.ngrok-free.dev'])

# Application 
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'two_factor',
    'core.apps.CoreConfig',
    'django.contrib.sites',
    'allauth',
    'allauth.account',            
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

SITE_ID = env.int('SITE_ID', default=1)

AUTHENTICATION_BACKENDS = [
    'core.auth_backends.CoreUsuarioBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', PROJECT_ROOT / 'frontend/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.session_user',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database configuration with environment variables
database_url = (env('DATABASE_URL', default='') or '').strip()
if database_url:
    DATABASES = {
        'default': dj_database_url.parse(database_url, conn_max_age=600),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST', default='localhost'),
            'PORT': env('DB_PORT'),
        }
    }

# --- CONFIGURACIÓN EXTREMA DE SEGURIDAD ---
# 1. Protección contra ataques comunes
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'  # Previene Clickjacking

# 2. Seguridad de Cookies (Strict para producción)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG  # Solo vía HTTPS en producción
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# 3. Seguridad CSRF
CSRF_TRUSTED_ORIGINS = [f"http://{host}" for host in ALLOWED_HOSTS] + [f"https://{host}" for host in ALLOWED_HOSTS]

# ── SEGURIDAD: Expiración de sesión por inactividad ─────────────────────────────────
# IMPORTANTE: SESSION_SAVE_EVERY_REQUEST = True PARA QUE EL EXPIRY SE GUARDE CORRECTAMENTE.
# Aunque se guarde en cada request, LA EXPIRACIÓN LA CONTROLA NUESTRO MIDDLEWARE
# (que verifica expiry_date con timezone.now()), no Django automáticamente.
SESSION_SAVE_EVERY_REQUEST = True  # ← Debe ser True para que set_expiry() se guarde

# Expiración de la cookie de sesión en segundos (1 minuto = 60)
SESSION_COOKIE_AGE = 60

# Clave de sesión para el middleware
SESSION_LAST_ACTIVITY_KEY = '_session_activity_ts'
SESSION_INACTIVITY_TIMEOUT = 60

# ── MIDDLEWARE personalizado de expiración por inactividad ────────────────────────
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.InactivitySessionMiddleware',  # ← Mover después de AuthenticationMiddleware
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# 4. HSTS (HTTP Strict Transport Security) - Solo activar con HTTPS
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True

# --- FIN CONFIGURACIÓN DE SEGURIDAD ---

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 6},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'es-co' # Ajustado a contexto latinoamericano (Cédula)
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static', PROJECT_ROOT / 'frontend/static']
STATIC_ROOT = PROJECT_ROOT / 'staticfiles'

# Media files (Cédulas, Selfies)
MEDIA_URL = '/media/'
MEDIA_ROOT = PROJECT_ROOT / 'media'

# Configuración de redirección de Login
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

TWO_FACTOR_PROFILE_URL = 'dashboard'
TWO_FACTOR_PATCH_ADMIN = False

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*']
ACCOUNT_EMAIL_VERIFICATION = 'none'

SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'prompt': 'select_account'},
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
GOOGLE_MAPS_API_KEY = env('GOOGLE_MAPS_API_KEY', default='')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' 
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='Soporte Assist Care <assistcoresoporte@gmail.com>')
SERVER_EMAIL = env('SERVER_EMAIL', default=EMAIL_HOST_USER)

EMERGENCY_SUPPORT_EMAIL = env('EMERGENCY_SUPPORT_EMAIL', default='')
EMERGENCY_SUPPORT_EMAILS = env.list('EMERGENCY_SUPPORT_EMAILS', default=[])

WOMPI_INTEGRITY_SECRET = env('WOMPI_INTEGRITY_SECRET', default='')

EPAYCO_P_CUST_ID_CLIENTE = env('EPAYCO_P_CUST_ID_CLIENTE', default='')
EPAYCO_P_KEY = env('EPAYCO_P_KEY', default='')
EPAYCO_PUBLIC_KEY = env('EPAYCO_PUBLIC_KEY', default='')
EPAYCO_WEBHOOK_DEBUG_TOKEN = env('EPAYCO_WEBHOOK_DEBUG_TOKEN', default='')
