# Generated by Django 5.2.14 on 2026-06-02 15:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('super_admin', 'Super admin'), ('admin', 'Admin'), ('discapacitado', 'Discapacitado'), ('enfermero', 'Enfermero')], max_length=20)),
                ('estado', models.CharField(choices=[('preregistro', 'Preregistro'), ('pendiente_revision', 'Pendiente revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='preregistro', max_length=30)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha_evento', models.DateTimeField()),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('asignada', 'Asignada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'peticiones',
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_postulacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'postulaciones',
            },
        ),
        migrations.CreateModel(
            name='PerfilDiscapacitado',
            fields=[
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_discapacitado', serialize=False, to='core.usuario')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('Otro', 'Otro')], max_length=10)),
                ('url_cedula', models.CharField(blank=True, max_length=500, null=True)),
                ('url_certificado_discapacidad', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'perfil_discapacitado',
            },
        ),
        migrations.CreateModel(
            name='PerfilEnfermero',
            fields=[
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_enfermero', serialize=False, to='core.usuario')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('Otro', 'Otro')], max_length=10)),
                ('telefono_whatsapp', models.CharField(max_length=20)),
                ('url_cedula', models.CharField(blank=True, max_length=500, null=True)),
                ('url_tarjeta_profesional', models.CharField(blank=True, max_length=500, null=True)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'perfil_enfermero',
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email', 'estado'], name='idx_usuarios_email_estado'),
        ),
        migrations.AddField(
            model_name='peticion',
            name='discapacitado',
            field=models.ForeignKey(db_column='discapacitado_id', on_delete=django.db.models.deletion.CASCADE, related_name='peticiones', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='enfermero',
            field=models.ForeignKey(db_column='enfermero_id', on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='peticion',
            field=models.ForeignKey(db_column='peticion_id', on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='core.peticion'),
        ),
        migrations.AddIndex(
            model_name='peticion',
            index=models.Index(fields=['ciudad', 'estado'], name='idx_peticiones_ciudad_estado'),
        ),
        migrations.AddConstraint(
            model_name='postulacion',
            constraint=models.UniqueConstraint(fields=('peticion', 'enfermero'), name='unica_postulacion'),
        ),
    ]
