# Generated by Django 5.2.14 on 2026-06-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfildiscapacitado',
            name='url_cedula',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='cedulas/'),
        ),
        migrations.AlterField(
            model_name='perfilenfermero',
            name='url_cedula',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='cedulas/'),
        ),
    ]
