# Generated by Django 5.2.14 on 2026-06-03 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_perfildiscapacitado_url_cedula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_logs', to='core.usuario')),
            ],
            options={
                'db_table': 'auditoria_logs',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='ServicioAcompanamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('En Camino', 'En Camino'), ('En Progreso', 'En Progreso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='En Camino', max_length=20)),
                ('origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('enfermero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_enfermero', to='core.usuario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_paciente', to='core.usuario')),
            ],
            options={
                'db_table': 'servicios_acompanamiento',
            },
        ),
    ]
