# Generated by Django 5.2.14 on 2026-06-03

import django.db.models.deletion
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditorialog_servicioacompanamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('enfermero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to='core.usuario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_realizadas', to='core.usuario')),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='core.servicioacompanamiento')),
            ],
            options={
                'db_table': 'calificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]

