# Generated by Django 5.2.14 on 2026-06-03

import django.db.models.deletion
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_calificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('enfermero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_emitidas_enfermero', to='core.usuario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas_paciente', to='core.usuario')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_paciente', to='core.servicioacompanamiento')),
            ],
            options={
                'db_table': 'calificaciones_paciente',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddConstraint(
            model_name='calificacionpaciente',
            constraint=models.UniqueConstraint(fields=('servicio', 'enfermero'), name='unica_calificacion_paciente_por_servicio'),
        ),
    ]

