# Generated by Django 5.2.14 on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_calificacionpaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildiscapacitado',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]

