# Generated by Django 5.2.6 on 2026-06-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_perfildiscapacitado_telefono_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioacompanamiento',
            name='peticion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='core.peticion'),
        ),
    ]

