# Generated by Django 5.2.14 on 2026-06-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servicioacompanamiento_peticion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildiscapacitado',
            name='acces_high_contrast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfildiscapacitado',
            name='acces_screen_reader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfildiscapacitado',
            name='acces_simplified_nav',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfildiscapacitado',
            name='biografia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='perfildiscapacitado',
            name='emergency_nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='perfildiscapacitado',
            name='emergency_parentesco',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='perfildiscapacitado',
            name='emergency_telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='perfildiscapacitado',
            name='historia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='perfilenfermero',
            name='biografia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='perfilenfermero',
            name='especialidad',
            field=models.CharField(blank=True, default='Registered Nurse', max_length=120),
        ),
    ]
