# Generated by Django 5.2.14 on 2026-06-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_perfildiscapacitado_acces_high_contrast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticion',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
