# Generated by Django 5.2.14 on 2026-06-04 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_peticion_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('incidencia', 'Incidencia'), ('auditoria', 'Auditoría'), ('rendimiento', 'Rendimiento')], default='incidencia', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='core.usuario')),
            ],
            options={
                'db_table': 'reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
