# Generated by Django 5.2.14 on 2026-06-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorialog',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
    ]

