# Generated by Django 5.2.14 on 2026-06-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auditorialog_archivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilenfermero',
            name='direccion_residencia',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='perfilenfermero',
            name='cuenta_tipo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilenfermero',
            name='cuenta_banco',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='perfilenfermero',
            name='cuenta_numero',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]

