# Generated by Django 5.2.14 on 2026-06-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_perfilenfermero_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildiscapacitado',
            name='foto_perfil',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='avatars/'),
        ),
    ]

