# Generated by Django 5.2.14 on 2026-06-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_perfildiscapacitado_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildiscapacitado',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfildiscapacitado',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfildiscapacitado',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
