# Generated by Django 5.2.14 on 2026-06-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_peticion_fecha_aceptacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticion',
            name='postulados',
            field=models.ManyToManyField(blank=True, related_name='servicios_postulados', through='core.Postulacion', to='core.usuario'),
        ),
    ]
