# Generated by Django 5.2.15 on 2026-06-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_configtarifas'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioacompanamiento',
            name='codigo_bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicioacompanamiento',
            name='codigo_intentos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicioacompanamiento',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
